name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # 👇 Install pnpm (stable version)
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true # Automatically run `pnpm install`

      # Build / test
      - run: pnpm build
      - run: pnpm test
